# Generated by Django 3.2.10 on 2022-01-18 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ganadores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('nombreCancion', models.CharField(max_length=40)),
                ('anioWin', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Karaoke',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreCancion', models.CharField(max_length=40)),
                ('artista', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Participantes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('edad', models.IntegerField()),
                ('anioInscripcion', models.DateField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
